// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubppgmbtrxtfecfnjrlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVicHBnbWJ0cnh0ZmVjZm5qcmxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzNDcyNDQsImV4cCI6MjA4NjkyMzI0NH0.cgwqJ0mXjuWesvlnZFfRjbyiI0Mezj5t2wzBZ6qIedI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});